# Generated by Django 5.2.7 on 2025-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_alter_student_group_alter_student_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.AddField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(related_name="student", to="school.teacher"),
        ),
    ]
